#define FLOW_TAP_TERM 70
#undef TAPPING_TERM
#define TAPPING_TERM 170

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "lXrnD/pjqXpd"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

